server:
  port: 8012

spring:
  application:
    name: register-server
  datasource:
    password: thinker@
    username: root
    url: jdbc:mysql://localhost:3306/micro_service
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8016/eureka/