spring:
  application:
    name: school-server
  cloud:
    nacos:
      server-addr: only:8848
      discovery:
        cluster-name: gz


server:
  port: 8016
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8016/eureka/