server:
  port: 8013


spring:
#  application:
#    name: info-server

  datasource:
    password: thinker@
    username: root
    url: jdbc:mysql://localhost:3306/micro_service
    driver-class-name: com.mysql.jdbc.Driver

#  cloud:
#    nacos:
#      server-addr: only:8848
#      discovery:
#        cluster-name: sz
#        namespace: 5ed0616b-e281-4855-89ec-6734a2421f50 # test namespace id


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 数据库下划线自动转驼峰标示关闭

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8016/eureka


# 仅仅只是对register-server有效；若是注入IRule的bean，则会对所有的服务起作用！！！
register-server:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  # 配置新的负载均衡规则
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 配置nacos负载均衡规则,替换了默认的轮询规则


# 开启饥饿加载，默认为懒加载
#ribbon:
#  eager-load:
#    enabled: true # 开启
#    clients:
#      - register-server # 服务开启的列表
a:
  b: a_b_local

# 配置feign的日志级别；也可以使用@Bean来注入
feign:
  client:
    config:
      default:  # 全部服务有效，可以指定服务
        loggerLevel: FULL  # 推荐使用None
  httpclient:
    enabled: true  # 开启apache httpclient的支持
    max-connections: 100
    max-connections-per-route: 40