server:
  port: 8888


spring:
  application:
    name: info-server-8013

  datasource:
    password: thinker@
    username: root
    url: jdbc:mysql://localhost:3306/micro_service
    driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 数据库下划线自动转驼峰标示关闭