server:
  port: 8018

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      server-addr: only:8848
    gateway:
      routes:
        - id: info-server  # 路由id，唯一标识
          uri: lb://info-server  # lb为loadBalance简写，负责负载均衡
          predicates:  # 断言，表达式
            - Path=/query/**  # 路径以query开头的url
            - After=2011-01-20T17:42:47.789-07:00[America/Denver]  # 参考 官网的路由断言工厂！
#          filters:
#            - AddRequestHeader=javaye, bigdata
      default-filters:
        - AddRequestHeader=javaye, bigdata1  # 全局拦截器
#        - id: register-server
#          uri: lb://register-server
#          predicates:
#            - Path=/query/**
#        - id: school-server
#          uri: lb://school-server
#          predicates:
#            - Path=/**
#      discovery:
#        cluster-name: sz